// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              int32
	DoctorID        int32
	PatientID       int32
	AppointmentDate pgtype.Date
}

type Doctor struct {
	ID         int32
	Name       string
	Speciality pgtype.Text
}

type Patient struct {
	ID   int32
	Name string
	Age  pgtype.Int4
}
